---
kind: pipeline
name: default

steps:
- name: test_esp
  image: python:alpine
  commands:
  - apk add --no-cache g++
  - pip3 install platformio
  - platformio update
  - pio test -e native

- name: build
  image: debian:buster-slim
  commands:
  - apt-get update
  - apt-get install -y --no-install-recommends make g++ python3-pip python3-setuptools python3-wheel
  - pip3 install platformio
  - platformio update
  - platformio platform install espressif8266
  - platformio lib install PubSubClient
  - "[ ! -e include/WifiParams.h ] && cp ci/WifiParams.h include/"
  - pio run -e d1_mini
  - cp ci/plantuml /usr/local/bin/
  - cd docs && LANG=C make | grep -q "Nothing to be done"

- name: test_nodejs
  image: node:alpine
  commands:
  - cd nodered
  - yarn add -D chai@latest @cucumber/cucumber
  - NODE_PATH=. node_modules/.bin/cucumber-js

- name: wait
  image: python:alpine
  depends_on:
    - test_esp
    - build
    - test_nodejs
---
kind: signature
hmac: 48f83ba580aa5bb0ffff7deca094f8e7904eb4c0f1708d18b14f5c4a81260f13

...
