---
kind: pipeline
name: default

steps:
- name: test
  image: python:alpine
  commands:
  - apk add --no-cache g++
  - pip3 install platformio
  - platformio update
  - pio test -e native

- name: build
  image: python:alpine
  commands:
  - apk add --no-cache g++
  - pip3 install platformio
  - platformio update
  - platformio platform install espressif8266
  - "[ ! -e include/WifiParams.h ] && cp ci/WifiParams.h include/"
  - pio run -e d1_mini

- name: wait
  image: python:alpine
  depends_on:
    - test
    - build
---
kind: signature
hmac: fbe9f12fb5c9e6449c337cf36d500f7dd5e2f320cdda3351553d50571d5f472e

...
