---
kind: pipeline
name: default

steps:
- name: test
  image: python:alpine
  commands:
  - apk add --no-cache g++
  - pip3 install platformio
  - platformio update
  - pio test -e native

- name: build
  image: python:alpine
  commands:
  - apk add --no-cache g++
  - pip3 install platformio
  - platformio update
  - "[ ! -e include/WifiParams.h ] && cp ci/WifiParams.h include/"
  - pio run -e d1_mini

- name: wait
  image: python:alpine
  depends_on:
    - test
    - build
---
kind: signature
hmac: 4fb38b6954040b70f475a5eb7c52224566762134de654c67d1418315642a8c98

...
