---
kind: pipeline
name: default

steps:
- name: test
  image: python:alpine
  commands:
  - apk add --no-cache g++
  - pip3 install platformio
  - platformio update
  - pio test -e native

- name: build
  image: debian:buster-slim
  commands:
  - apt-get update
  - apt-get install -y --no-install-recommends make g++ python3-pip python3-setuptools python3-wheel
  - pip3 install platformio
  - platformio update
  - platformio platform install espressif8266
  - platformio lib install PubSubClient
  - "[ ! -e include/WifiParams.h ] && cp ci/WifiParams.h include/"
  - pio run -e d1_mini
  - cd docs && LANG=C make | grep -q "up to date"

- name: wait
  image: python:alpine
  depends_on:
    - test
    - build
---
kind: signature
hmac: 904b698ea340f2b27bf6545a79a1332d23e9db789f06e3eab4703346141c1dbf

...
