---
kind: pipeline
name: default

steps:
- name: test
  image: python:alpine
  commands:
  - apk add --no-cache g++
  - pip3 install platformio
  - platformio update
  - pio test -e native

- name: build
  image: debian:buster-slim
  commands:
  - apt-get update
  - apt-get install g++ python3-pip
  - pip3 install platformio
  - platformio update
  - platformio platform install espressif8266
  - "[ ! -e include/WifiParams.h ] && cp ci/WifiParams.h include/"
  - pio run -e d1_mini

- name: wait
  image: python:alpine
  depends_on:
    - test
    - build
---
kind: signature
hmac: 0a64476d47075043c5f1707ab28b38ed48bad7cae9284a14354fe86385a79a8f

...
