---
kind: pipeline
name: default

steps:
- name: test
  image: python:alpine
  commands:
  - apk add --no-cache g++
  - pip3 install platformio
  - platformio update
  - pio test -e native

- name: build
  image: debian:buster-slim
  commands:
  - apt-get update
  - apt-get install -f --no-install-recommends g++ python3-pip
  - pip3 install platformio
  - platformio update
  - platformio platform install espressif8266
  - "[ ! -e include/WifiParams.h ] && cp ci/WifiParams.h include/"
  - pio run -e d1_mini

- name: wait
  image: python:alpine
  depends_on:
    - test
    - build
---
kind: signature
hmac: 117f0f214074591524f583297f3a8d7839f9697e81f275ca926f86b95ffbdc3d

...
