---
kind: pipeline
name: default

steps:
- name: test
  image: python:alpine
  commands:
  - apk add --no-cache g++
  - pip3 install platformio
  - platformio update
  - pio test -e native

- name: build
  image: debian:buster-slim
  commands:
  - apt-get update
  - apt-get install -y --no-install-recommends g++ python3-pip python3-setuptools
  - pip3 install platformio
  - platformio update
  - platformio platform install espressif8266
  - platformio lib install PubSubClient
  - "[ ! -e include/WifiParams.h ] && cp ci/WifiParams.h include/"
  - pio run -e d1_mini

- name: wait
  image: python:alpine
  depends_on:
    - test
    - build
---
kind: signature
hmac: 6056d6a8f89748266507444b1377cfef0fb1e754035d2c2f600054aa530f37fe

...
