---
kind: pipeline
name: default

steps:
- name: test
  image: python:alpine
  commands:
  - apk add --no-cache g++
  - pip3 install platformio
  - platformio update
  - pio test -e native

- name: build
  image: debian:buster-slim
  commands:
  - apt-get update
  - apt-get install -y --no-install-recommends make g++ python3-pip python3-setuptools python3-wheel plantuml
  - pip3 install platformio
  - platformio update
  - platformio platform install espressif8266
  - platformio lib install PubSubClient
  - "[ ! -e include/WifiParams.h ] && cp ci/WifiParams.h include/"
  - pio run -e d1_mini
  - cd docs && LANG=C make | grep -q "up to date"

- name: wait
  image: python:alpine
  depends_on:
    - test
    - build
---
kind: signature
hmac: a1405189c8e1131f25fb2599e18c24b2710caa5b55b90efe2e1e0d2ea574f7ee

...
